title: Amuzik
author: Héctor Martín Ortega
email: hecmaror04@gmail.com
description: "Proyecto de fin de ciclo: Media Player con sincronización en tiempo real."

remote_theme: pages-themes/cayman@v0.2.0

markdown: kramdown
plugins:
  - jekyll-remote-theme  # Habilita temas remotos en GitHub Pages

social:
  github: hmarort
  instagram: hmarort
  
show_downloads: true
