title: Amuzik - Proyecto de Fin de Ciclo
author: Héctor Martín Ortega
email: hecmaror04@gmail.com

description: "Proyecto de fin de ciclo: Media Player con sincronización en tiempo real."

remote_theme: jekyll-theme-cayman

# Configuración de Markdown
markdown: kramdown
