# Site settings
title: Amuzik
description: Aplicación de reproducción de música con sincronización en tiempo real entre usuarios
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima

# Includes
include:
  - _includes

# Exclude
exclude:
  - LICENSE
  - README.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
project_name: Amuzik
project_type: Aplicación de reproducción de música
inspiration: Spotify + Spicetify
objective: Permitir a los usuarios escuchar la misma canción al mismo tiempo desde diferentes lugares

# Frontend technologies
frontend_framework: Ionic 7 con Angular
frontend_language: TypeScript
frontend_ui: TailwindCSS

# Backend technologies
backend_language: PHP
backend_framework: CodeIgniter4 (API REST)
database: PostgreSQL
authentication: JWT (JSON Web Token)

# External APIs
music_api: SoundCloud API
realtime_sync: WebSockets (PHP Ratchet o Node.js)

# Navigation
header_pages:
  - README.md

# Footer
footer:
  include: footer.html

# Sidebar
sidebar:
  include: sidebar.html
