title: Amuzik - Proyecto de Fin de Ciclo
author: Héctor Martín Ortega
email: tuemail@example.com

# Descripción corta que aparecerá en la cabecera del sitio
description: "Proyecto de fin de ciclo: Media Player con sincronización en tiempo real."

# Tema moderno y atractivo
remote_theme: jekyll-theme-cayman

# Configuración de Markdown
markdown: kramdown

# Configuraciones extra para mejorar la apariencia
show_downloads: true

# Enlaces a redes o repositorio
github:
  is_project_page: true
  repository_url: "https://github.com/hmarort/amuzik"

# Plugins adicionales (si necesitas extras, agrégalos aquí)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
